cswp/config/routes.rb
#---
# Excerpted from "The Way of the Web Tester",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/jrtest for more book information.
#---
Rails.application.routes.draw do

  resources :permits

  get 'static_pages/home'

  resources :users

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    'tracker' => 'tracker#new'
  post   'tracker' => 'tracker#update'

end

cswp/app/models/permit.rb
#---
# Excerpted from "The Way of the Web Tester",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/jrtest for more book information.
#---
class Permit < ActiveRecord::Base
end

cswp/app/controllers/permits_controller.rb
#---
# Excerpted from "The Way of the Web Tester",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/jrtest for more book information.
#---
class PermitsController < ApplicationController
  before_action :set_permit, only: [:show, :edit, :update, :destroy]

  # GET /permits
  # GET /permits.json
  def index
    @permits = Permit.all
  end

  # GET /permits/1
  # GET /permits/1.json
  def show
  end

  # GET /permits/new
  def new
    @permit = Permit.new
    @locations = ['Saskatoon']
  end

  # GET /permits/1/edit
  def edit
  end

  # POST /permits
  # POST /permits.json
  def create
    @permit = Permit.new(permit_params)

    respond_to do |format|
      if @permit.save
        flash[:success] = 'Permit was successfully created.'
        format.html { redirect_to @permit }
        format.json { render :show, status: :created, location: @permit }
      else
        format.html { render :new }
        format.json { render json: @permit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permits/1
  # PATCH/PUT /permits/1.json
  def update
    respond_to do |format|
      if @permit.update(permit_params)
        flash[:success] = 'Permit was successfully updated.'
        format.html { redirect_to @permit }
        format.json { render :show, status: :ok, location: @permit }
      else
        format.html { render :edit }
        format.json { render json: @permit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permits/1
  # DELETE /permits/1.json
  def destroy
    @permit.destroy
    flash[:success] = 'Permit was successfully destroyed.'
    respond_to do |format|
      format.html { redirect_to permits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permit
      @permit = Permit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permit_params
      params.require(:permit).permit(:location)
    end
end

cswp/app/helpers/permits_helper.rb
#---
# Excerpted from "The Way of the Web Tester",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/jrtest for more book information.
#---
module PermitsHelper
end

cswp/app/views/permits/_form.html.erb
<%= form_for(@permit) do |f| %>
    <div class="field">
      <%= f.label :location %><br>
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
    </div>
<% end %>

cswp/app/views/permits/edit.html.erb
<% provide(:title, 'Edit Permit') %>

<div class="row">
  <div class="col-md-4">
    <h1>Editing Permit</h1>
    <%= render 'form' %>
    <%= link_to 'Show', @permit %> |
    <%= link_to 'Back', permits_path %>
  </div>
</div>

cswp/app/views/permits/index.html.erb
<h1>Listing permits</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @permits.each do |permit| %>
      <tr>
        <td><%= permit.location %></td>
        <td><%= link_to 'Show', permit %></td>
        <td><%= link_to 'Edit', edit_permit_path(permit) %></td>
        <td><%= link_to 'Destroy', permit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Permit', new_permit_path %>

cswp/app/views/permits/new.html.erb
<% provide(:title, 'Create Permit') %>

<div class="row">
  <div class="col-md-4">
    <h1>Create Permit</h1>
    <%= render 'form' %>
    <%= link_to 'Back', permits_path %>
  </div>
</div>

cswp/app/views/permits/show.html.erb
<% provide(:title, "Show Permit") %>

<div class="row">
  <div class="col-md-4">

    <p>
      <strong>Location:</strong>
      <%= @permit.location %>
    </p>

    <%= link_to 'Edit', edit_permit_path(@permit) %> |
    <%= link_to 'Back', permits_path %>
  </div>
</div>